
@startuml
interface SnowmanComponent {
+sing(): String
}

class ConcreteSnowman implements SnowmanComponent {
+sing(): String
}

abstract class SnowmanDecorator implements SnowmanComponent {
#decoratedSnowman: SnowmanComponent
  +GlovesDecorator(decoratedSnowman:SnowmanComponent)
  +sing(): String
}

class ScarfDecorator extends SnowmanDecorator {
  +GlovesDecorator(decoratedSnowman)
+sing(): String
}

class HatDecorator extends SnowmanDecorator {
  +GlovesDecorator(decoratedSnowman)
  +sing(): String
}

class GlovesDecorator extends SnowmanDecorator {
  +GlovesDecorator(decoratedSnowman)
  +sing(): String
}

SnowmanDecorator o-- SnowmanComponent : decoratedSnowman

@enduml