@startuml
interface USATariffSubject {
  +addObserver(observer: Consumer<Double>): void
  +setTariff(newTariff: double): void
}

class USATariff implements USATariffSubject {
  -tariff: double
  -observers: List<Consumer<Double>>
  +USATariff(initialTariff: double)
  +addObserver(observer: Consumer<Double>): void
  +removeObserver(observer: Consumer<Double>): void
  -notifyObservers(tariffIncrease: double): void
  +setTariff(newTariff: double): void
}

interface Consumer<T> {
  +accept(t: T): void
}

class Country implements Consumer<Double> {
  -name: String
  +accept(tariffIncrease: double): void
}

class Company implements Consumer<Double> {
  -name: String
  +accept(tariffIncrease: double): void
}

USATariff "1" o- "*" Consumer : observers

@enduml